[build]
  functions = "functions"  # Path where your serverless functions are
  publish = "public"       # Folder for your static assets (index.html)

[[redirects]]
  from = "/api/payment:token"
  to = "/.netlify/functions/payment"
  status = 200
